#nome do workflow
name: Meu primeiro workflow
on: workflow_dispatch
#coleção de jobs
jobs:
  #nome do primeiro job
  primeiro_job:
    #runner desse job
    runs-on: ubuntu-latest
    #coleção de steps deste job
    steps:
      #primeiro step
      - name: Hello, Github Actions!
        run: echo "Hello, Github Actions!"
      #segundo step
      - name: Qual o diretório atual?
        run: pwd
      #terceiro step
      - name: Qual o conteúdo do diretório atual, incluindo arquivos ocultos?
        run: ls -a
      #quarto step
      - name: Até mais!
        run: "See you, Github Actions"
